apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
    project: spmia
spec:
  selector:
    app: database
    project: spmia
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
