
#   kubectl run database \
#     --image=postgres:10 \
#     --env="POSTGRES_USER=postgres_dev" \
#     --env="POSTGRES_PASSWORD=p0stgr@s_dev" \
#     --env="POSTGRES_DB=eagle_eye_dev" \
#     --port=5432 \
#     --expose=true \
#     --restart="Always" \
#     --labels="app=database,project=spmia"

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    project: spmia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      project: spmia
  template:
    metadata:
      labels:
        app: database
        project: spmia
    spec:
      restartPolicy: Always
      containers:
      - name: database
        image: postgres:10
        env:
        - name: POSTGRES_USER
          value: postgres_dev
        - name: POSTGRES_PASSWORD
          value: p0stgr@s_dev
        - name: POSTGRES_DB
          value: eagle_eye_dev
        ports:
        - containerPort: 5432
          protocol: TCP
