apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkaserver
  labels:
    project: spmia
    app: kafkaserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: spmia
        app: kafkaserver
    spec:
      restartPolicy: Always
      containers:
        - name: kafkaserver
          image: spotify/kafka
          ports:
            - containerPort: 2181
            - containerPort: 9092
          resources:
            limits:
              memory: "1073741824"
