apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.16.0 (0c01309)
    project: spmia
  creationTimestamp: null
  labels:
    io.kompose.service: authenticationservice
  name: authenticationservice
spec:
  ports:
  - name: "8901"
    port: 8901
    targetPort: 8901
  selector:
    io.kompose.service: authenticationservice
  type: NodePort
status:
  loadBalancer: {}
