apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.16.0 (0c01309)
    project: spmia
  creationTimestamp: null
  labels:
    io.kompose.service: configserver
  name: configserver
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: configserver
  type: NodePort
status:
  loadBalancer: {}
