apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.16.0 (0c01309)
    project: spmia
  creationTimestamp: null
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: eurekaserver
    spec:
      containers:
      - image: johncarnell/tmx-eurekasvr:cb1
        name: eurekaserver
        ports:
        - containerPort: 8761
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: Always
status: {}
