apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.16.0 (0c01309)
    project: spmia
  creationTimestamp: null
  labels:
    io.kompose.service: zuulserver
  name: zuulserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zuulserver
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_URI
          value: http://configserver:8888
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: PROFILE
          value: default
        - name: SERVER_PORT
          value: "5555"
        image: johncarnell/tmx-zuulsvr:cb1
        name: zuulserver
        ports:
        - containerPort: 5555
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: Always
status: {}
